sudo: required
dist: trusty
language: node_js
notifications:
  hipchat:
    rooms:
      secure: l5TTd5JuPAW883PtcyaIBcJI9Chr9JpsZPQAEUBKAgIEwzuS6y7t5arlkS1PwH6gi1FADzYDf+OXSIou4GkTSrIetnBcT/SAgF0gBKgIhj+eRkuCfZ4VaC7BPhfZ0hgYRE+5Ejf5BM2MJafRm0pj7OlqG4xKrQZwtuV1te5r3JY=
  irc:
    channels:
      - "chat.freenode.net#videojs"
    use_notice: true
before_script:
  # always install the appropriate version of video.js for the environment
  - npm i "video.js@$VJS";
env:
  - VJS=5
  - VJS=6
addons:
  firefox: latest
  chrome: stable
